<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="186" started-at="2021-03-10T15:20:21Z" finished-at="2021-03-10T15:20:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="186" started-at="2021-03-10T15:20:21Z" finished-at="2021-03-10T15:20:21Z">
      <class name="salesTestCases.Tc_Sales_005_POS_BillActivity">
        <test-method status="FAIL" signature="APKConfig()[pri:0, instance:salesTestCases.Tc_Sales_005_POS_BillActivity@3e57cd70]" name="APKConfig" is-config="true" duration-ms="26715" started-at="2021-03-10T20:49:54Z" finished-at="2021-03-10T20:50:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.UBQPageObjectLib.LoginPage.login(LoginPage.java:88)
	at com.UBQGenericLib.APKConfiguration.APKConfig(APKConfiguration.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- APKConfig -->
        <test-method status="SKIP" signature="LoadMethods()[pri:0, instance:salesTestCases.Tc_Sales_005_POS_BillActivity@3e57cd70]" name="LoadMethods" is-config="true" duration-ms="0" started-at="2021-03-10T20:50:21Z" finished-at="2021-03-10T20:50:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoadMethods -->
        <test-method status="SKIP" signature="OrderCreationAndVerification()[pri:0, instance:salesTestCases.Tc_Sales_005_POS_BillActivity@3e57cd70]" name="OrderCreationAndVerification" duration-ms="0" started-at="2021-03-10T20:50:21Z" finished-at="2021-03-10T20:50:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.UBQPageObjectLib.LoginPage.login(LoginPage.java:88)
	at com.UBQGenericLib.APKConfiguration.APKConfig(APKConfiguration.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderCreationAndVerification -->
      </class> <!-- salesTestCases.Tc_Sales_005_POS_BillActivity -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
